sudo: false
language: c

addons:
    apt_packages:
        - lib32stdc++6

env:
    global:
        - secure: JUNQHC6mafptpSpQqsQJNqhqg4hLfgrBEZFXRmPePXKSqcaoC4NnH7Fx1vGDQANHIgAspNDAhmbs7HY4bP43zJ24c+XuObpDn3TZmIHM0/yKZ/04vDdZIR09dk1qXt4zlTakT2jfuSm1YbCU5UI5NDKJryksY9eiK1VC/X9Ji+Ha2CJyj+I00jTYNfuqmu9BIFyvl26sMocfj3GEv9YIH77u+YXiCW4UDGKkb54LwznfUvqNdAa11visEQr9uK1uB9iwIo8lcfM6qEOMAmk84PvP2uOcCtUG92ryV+w+pege90xtlX4wy94N5xbx7kiEkfLMZpVolVv2HAkL4cmnAjEpv8orJYt8sc88Y2dilfrOnQqYEtI0kJvNsrwdYudPmmMLSxcHw6nWfBJ23k159dn3qeHuJQ1mCB/2ahEkZJsgqVt+9lwbFT2UU8tOqYOoaG8oC2dkYa0ZuNgcqbXZmUKfENizmf7kI8SzhBryoYA61G2YZ0HmwN4XROIcXpiNxIDFcKyxC/xzMmTm69xLSrmUmP1uaJdgY405pe8CyJVniaExx54LM8j0t/l48xI5EjkX9IpEVjHoa2OI8S2ph/LXtYNOgH0vV/4F6dUWZcyPZs2CQCA5eS3Gi0t67POdhgx8f374/G0RxlmLa4PcQh3+9nEDMj9EKpH7GO4/By0=
    matrix:
        - SOURCEMOD=1.10
        - SOURCEMOD=1.11

before_script:
    - mkdir build && cd build
    - wget "http://www.sourcemod.net/latest.php?version=$SOURCEMOD&os=linux" -O sourcemod-$SOURCEMOD-linux.tar.gz
    - tar -xzf sourcemod-$SOURCEMOD-linux.tar.gz
    - cd addons/sourcemod/scripting
    - chmod +x spcomp
    - cp -R $TRAVIS_BUILD_DIR/addons/sourcemod/scripting/* .

script: ./compile.sh advertisements.sp

before_deploy:
    - cp -R compiled/* $TRAVIS_BUILD_DIR/addons/sourcemod/plugins/
    - cd $TRAVIS_BUILD_DIR
    - tar -czf release.tar.gz addons/
    - sed -e "s/\$TRAVIS_TAG/$TRAVIS_TAG/" update.txt.template > update.txt
    - git config user.name "Travis CI"
    - git config user.email "travis@example.com"
    - git remote set-url origin https://ErikMinekus:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    - git checkout --orphan gh-pages
    - git rm -rf .
    - git add addons/ update.txt
    - git commit -m "Deploy to GitHub Pages"
    - git push --force --quiet origin gh-pages > /dev/null 2>&1

deploy:
    provider: releases
    api_key:
        secure: l298wqXu+PkzKVKLDL+OSS/Uie4wbtcW9bNmqo1G7c38Yr1gdJoztYM0N1yXZxWdsHGjZi1gQ6GnS8kEmp6duDp8Q7Ou8TWBYhzHM7Ye0XFsHhISBtBpSunVbqMxD1yJDuT9Rg0f8+TgiSXGY86E3x2F8lHoFXjFiVNv8dWd0cDDzXGE43bFhDtle0Rm9tXJfRe1E7yPIMe6epbUZpUL5Dp244b7xirjfxOhFseirwVy+cmCZVehOoUKuIpVuKoKijAJzP/v1g79y3ZtaRKVn+1bV0seqOBcwmWSy5QlmwomSpxNsbERJ0dc7TTTw5W5ldzCK2bHOTEFQyE4dJ1OSuw4J9Tx3i/Dfp4UDpPif0ME7i/wOmy5X6uwc3puou51AemTqDmnbI6ROvKzep3AofsDklrtqQxJ6fscsJpy92lD9Ql/eVOy+wphwYAR5T+YsDfNOk0EpFeolIwAs4iky/e1nL9aAp+DdjacGTRpJPfmZc/etXAvLhaJ1yy49NwPmm28YDQf2AARk2WpDDI+Kw2tdqKDcviRlGId5Tn0jEB13xtDqEplTuye078L+Rqumcq7a4744x1oudZ+62sEJ1pc2Z2i3v6Fr160oWl/FJ0jOxt302Kk8v5or94nFr3/xka+Tq51knXL85A3DLZ/P385fIk28t47/1mp7wFPysI=
    file: release.tar.gz
    skip_cleanup: true
    on:
        tags: true
        condition: $SOURCEMOD = 1.10
